### ISSUE TITLE
lgpl

### ISSUE THREAD

**Issue by tylerjw** [PickNikRobotics/ros_reflexxes#11]
This library has the LGPL: http://www.gnu.org/licenses/lgpl-3.0.en.html

We should make that clear with an included license file and make sure we are being careful about how we use this so as to not violate the LGPL.

Generally, we should probably only dynamically link against this.  And, even then we are required to list this and the LGPL with our licenses when we do.

**Comment by tylerjw** [comment]
> 5. Combined Libraries.

> You may place library facilities that are a work based on the Library side by side in a single library together with other library facilities that are not Applications and are not covered by this License, and convey such a combined library under terms of your choice, if you do both of the following:

>    a) Accompany the combined library with a copy of the same work based on the Library, uncombined with any other library facilities, conveyed under the terms of this License.
>    b) Give prominent notice with the combined library that part of it is a work based on the Library, and explaining where to find the accompanying uncombined form of the same work.

**Comment by AndyZe** [comment]
Let me try to parse this, bit-by-bit:

> You may place library facilities that are a work based on the Library side by side in a single library together with other library facilities that are not Applications and are not covered by this License

OK, that's pretty much what we do with `reflexxes_wrapper` except it's only header files, not a library. It might become a library later.

> a) Accompany the combined library with a copy of the same work based on the Library, uncombined with any other library facilities, conveyed under the terms of this License.

OK, we do that.

> b) Give prominent notice with the combined library that part of it is a work based on the Library, and explaining where to find the accompanying uncombined form of the same work.

That's done in the README already. I'll add a link to Reflexxes to be on the safe side

**Comment by AndyZe** [comment]
Fixed by #13 and #14
